#include "core_internal.h"
#include "sloph/context.h"

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { const char **names; SlophCoreType **types; size_t count; } Env;
typedef struct {
    SlophContext *ctx; SlophCoreUnit *unit;
    const char **all_binders; size_t binder_count, binder_cap;
    SlophCoreType **temps; size_t temp_count, temp_cap;
} Check;

static SlophSpan sp(SlophCoreSpan s) { SlophSpan r = {s.start, s.end}; return r; }
static SlophStatus fail(Check *c, const char *code, const char *message, SlophCoreSpan s) {
    SlophStatus r = sloph_context_add_diagnostic(c->ctx, code, "validate", message, sp(s));
    return r == SLOPH_STATUS_OK ? SLOPH_STATUS_INVALID_ARGUMENT : r;
}
static SlophStatus fail_details(Check*c,const char*code,const char*message,const char*details,SlophCoreSpan s){SlophStatus r=sloph_context_add_diagnostic_full(c->ctx,code,"validate",message,details,sp(s),SLOPH_SEVERITY_ERROR);return r==SLOPH_STATUS_OK?SLOPH_STATUS_INVALID_ARGUMENT:r;}
static void text_add(char*out,size_t cap,size_t*len,const char*s){size_t n=strlen(s);if(*len<cap-1u){if(n>cap-1u-*len)n=cap-1u-*len;memcpy(out+*len,s,n);*len+=n;out[*len]=0;}}
static void type_text(const SlophCoreType*t,char*out,size_t cap,size_t*len){size_t i;switch(t->kind){case SLOPH_TYPE_INT:text_add(out,cap,len,"Int");break;case SLOPH_TYPE_BYTES:text_add(out,cap,len,"Bytes");break;case SLOPH_TYPE_NAMED:text_add(out,cap,len,"(named ");text_add(out,cap,len,t->as.name);text_add(out,cap,len,")");break;case SLOPH_TYPE_VARIABLE:text_add(out,cap,len,"(var ");text_add(out,cap,len,t->as.name);text_add(out,cap,len,")");break;case SLOPH_TYPE_APPLIED:text_add(out,cap,len,"(apply ");text_add(out,cap,len,t->as.applied.constructor);for(i=0;i<t->as.applied.count;++i){text_add(out,cap,len," ");type_text(t->as.applied.items[i],out,cap,len);}text_add(out,cap,len,")");break;case SLOPH_TYPE_FUNCTION:text_add(out,cap,len,"(fn ");if(strcmp(t->as.function.mode,"own")){text_add(out,cap,len,t->as.function.mode);text_add(out,cap,len," ");}type_text(t->as.function.parameter,out,cap,len);text_add(out,cap,len," ");type_text(t->as.function.result,out,cap,len);text_add(out,cap,len,")");break;case SLOPH_TYPE_FORALL:text_add(out,cap,len,"(forall ");text_add(out,cap,len,t->as.forall.parameter);text_add(out,cap,len," ");type_text(t->as.forall.body,out,cap,len);text_add(out,cap,len,")");break;}}
static bool segment(const char *s, size_t n) {
    size_t i;
    if (!n || !((s[0]>='A'&&s[0]<='Z')||(s[0]>='a'&&s[0]<='z')||s[0]=='_')) return false;
    for (i=1;i<n;++i) if (!((s[i]>='A'&&s[i]<='Z')||(s[i]>='a'&&s[i]<='z')||(s[i]>='0'&&s[i]<='9')||s[i]=='_')) return false;
    return true;
}
static bool local_id(const char *s) { return segment(s, strlen(s)); }
static bool global_id(const char *s) {
    const char *p=s; size_t n=0;
    for (;;) { const char *q=strstr(p,"::"); size_t z=q?(size_t)(q-p):strlen(p); if(!segment(p,z))return false; ++n; if(!q)break; p=q+2; }
    return n>=2;
}
static SlophCoreEnum *enum_find(Check *c,const char *n) { size_t i; for(i=0;i<c->unit->type_count;++i)if(!strcmp(c->unit->types[i].name,n))return &c->unit->types[i]; return NULL; }
static SlophCoreDefinition *def_find(Check *c,const char *n) { size_t i; for(i=0;i<c->unit->definition_count;++i)if(!strcmp(c->unit->definitions[i].name,n))return &c->unit->definitions[i]; return NULL; }
static SlophCoreConstructor *con_find(Check *c,const char *n,SlophCoreEnum **e) { size_t i,j; for(i=0;i<c->unit->type_count;++i)for(j=0;j<c->unit->types[i].constructor_count;++j)if(!strcmp(c->unit->types[i].constructors[j].name,n)){*e=&c->unit->types[i];return &c->unit->types[i].constructors[j];} return NULL; }
static bool equal(const SlophCoreType *a,const SlophCoreType *b) {
    size_t i; if(!a||!b||a->kind!=b->kind)return false;
    switch(a->kind){
    case SLOPH_TYPE_INT:case SLOPH_TYPE_BYTES:return true;
    case SLOPH_TYPE_NAMED:case SLOPH_TYPE_VARIABLE:return !strcmp(a->as.name,b->as.name);
    case SLOPH_TYPE_APPLIED:if(strcmp(a->as.applied.constructor,b->as.applied.constructor)||a->as.applied.count!=b->as.applied.count)return false;for(i=0;i<a->as.applied.count;++i)if(!equal(a->as.applied.items[i],b->as.applied.items[i]))return false;return true;
    case SLOPH_TYPE_FUNCTION:return !strcmp(a->as.function.mode,b->as.function.mode)&&equal(a->as.function.parameter,b->as.function.parameter)&&equal(a->as.function.result,b->as.function.result);
    case SLOPH_TYPE_FORALL:return !strcmp(a->as.forall.parameter,b->as.forall.parameter)&&equal(a->as.forall.body,b->as.forall.body);
    } return false;
}
static char *dupstr(const char *s){size_t n=strlen(s)+1u;char *r=(char*)malloc(n);if(r)memcpy(r,s,n);return r;}
static SlophCoreType *clone_sub(const SlophCoreType *t,const char *name,const SlophCoreType *replacement) {
    SlophCoreType *r; size_t i;
    if(t->kind==SLOPH_TYPE_VARIABLE&&!strcmp(t->as.name,name))t=replacement;
    r=(SlophCoreType*)calloc(1u,sizeof(*r));if(!r)return NULL;r->kind=t->kind;
    switch(t->kind){
    case SLOPH_TYPE_INT:case SLOPH_TYPE_BYTES:break;
    case SLOPH_TYPE_NAMED:case SLOPH_TYPE_VARIABLE:r->as.name=dupstr(t->as.name);if(!r->as.name)goto bad;break;
    case SLOPH_TYPE_APPLIED:r->as.applied.constructor=dupstr(t->as.applied.constructor);r->as.applied.count=t->as.applied.count;r->as.applied.items=(SlophCoreType**)calloc(t->as.applied.count,sizeof(*r->as.applied.items));if(!r->as.applied.constructor||(t->as.applied.count&&!r->as.applied.items))goto bad;for(i=0;i<t->as.applied.count;++i)if(!(r->as.applied.items[i]=clone_sub(t->as.applied.items[i],name,replacement)))goto bad;break;
    case SLOPH_TYPE_FUNCTION:r->as.function.mode=dupstr(t->as.function.mode);r->as.function.parameter=clone_sub(t->as.function.parameter,name,replacement);r->as.function.result=clone_sub(t->as.function.result,name,replacement);if(!r->as.function.mode||!r->as.function.parameter||!r->as.function.result)goto bad;break;
    case SLOPH_TYPE_FORALL:r->as.forall.parameter=dupstr(t->as.forall.parameter);r->as.forall.body=clone_sub(t->as.forall.body,!strcmp(t->as.forall.parameter,name)?"":name,replacement);if(!r->as.forall.parameter||!r->as.forall.body)goto bad;break;
    }return r;
bad:sloph_core_type_destroy(r);return NULL;
}
static SlophStatus temp(Check*c,SlophCoreType*t,SlophCoreType**out){
    if(!t)return SLOPH_STATUS_OUT_OF_MEMORY;
    if(c->temp_count==c->temp_cap){size_t z=c->temp_cap?c->temp_cap*2u:16u;SlophCoreType**p=(SlophCoreType**)realloc(c->temps,z*sizeof(*p));if(!p){sloph_core_type_destroy(t);return SLOPH_STATUS_OUT_OF_MEMORY;}c->temps=p;c->temp_cap=z;}
    c->temps[c->temp_count++]=t;*out=t;return SLOPH_STATUS_OK;
}
static bool scoped(const char **v,size_t n,const char*s){size_t i;for(i=0;i<n;++i)if(!strcmp(v[i],s))return true;return false;}
static SlophStatus wf(Check*c,SlophCoreType*t,SlophCoreSpan s,const char**vars,size_t n){
    size_t i;SlophCoreEnum*e;SlophStatus r;
    switch(t->kind){
    case SLOPH_TYPE_INT:return SLOPH_STATUS_OK;
    case SLOPH_TYPE_BYTES:return c->unit->version?SLOPH_STATUS_OK:fail(c,"core.validate.bytes_version","Bytes requires Core version 1 or later",s);
    case SLOPH_TYPE_NAMED:e=enum_find(c,t->as.name);if(!e)return fail(c,"core.validate.unknown_type","unknown nominal type",s);return e->type_parameter_count?fail(c,"core.validate.type_arity","generic type requires type arguments",s):SLOPH_STATUS_OK;
    case SLOPH_TYPE_VARIABLE:if(scoped(vars,n,t->as.name))return SLOPH_STATUS_OK;{char message[256],details[256];(void)snprintf(message,sizeof(message),"free type variable '%s'",t->as.name);(void)snprintf(details,sizeof(details),"{\"variable\":\"%s\"}",t->as.name);return fail_details(c,"core.validate.free_type_variable",message,details,s);}
    case SLOPH_TYPE_APPLIED:e=enum_find(c,t->as.applied.constructor);if(!e)return fail(c,"core.validate.unknown_type","unknown nominal type",s);if(e->type_parameter_count!=t->as.applied.count)return fail(c,"core.validate.type_arity","type has wrong argument count",s);for(i=0;i<t->as.applied.count;++i)if((r=wf(c,t->as.applied.items[i],s,vars,n))!=SLOPH_STATUS_OK)return r;return SLOPH_STATUS_OK;
    case SLOPH_TYPE_FUNCTION:if(strcmp(t->as.function.mode,"own")&&strcmp(t->as.function.mode,"borrow"))return fail(c,"core.validate.parameter_mode","parameter mode must be own or borrow",s);if(strcmp(t->as.function.mode,"own")&&c->unit->version!=3)return fail(c,"core.validate.parameter_mode_version","borrow parameters require Core version 3",s);r=wf(c,t->as.function.parameter,s,vars,n);return r==SLOPH_STATUS_OK?wf(c,t->as.function.result,s,vars,n):r;
    case SLOPH_TYPE_FORALL:{const char**nv;if(c->unit->version<2)return fail(c,"core.validate.generic_version","universal types require Core version 2 or later",s);if(scoped(vars,n,t->as.forall.parameter))return fail(c,"core.validate.duplicate_type_parameter","duplicate type parameter",s);nv=(const char**)malloc((n+1u)*sizeof(*nv));if(!nv)return SLOPH_STATUS_OUT_OF_MEMORY;if(n)memcpy(nv,vars,n*sizeof(*nv));nv[n]=t->as.forall.parameter;r=wf(c,t->as.forall.body,s,nv,n+1u);free(nv);return r;}
    }return fail(c,"core.validate.type_form","unknown Core type representation",s);
}
static SlophCoreType *env_get(Env e,const char*n){size_t i=e.count;while(i){--i;if(!strcmp(e.names[i],n))return e.types[i];}return NULL;}
static SlophStatus binder(Check*c,SlophCoreBinder*b,const char**vars,size_t n){size_t i;if(!local_id(b->name))return fail(c,"core.validate.local_identity","invalid local identity",b->span);for(i=0;i<c->binder_count;++i)if(!strcmp(c->all_binders[i],b->name))return fail(c,"core.validate.duplicate_local","local binder is reused in one definition",b->span);if(c->binder_count==c->binder_cap){size_t z=c->binder_cap?c->binder_cap*2u:16u;const char**p=(const char**)realloc(c->all_binders,z*sizeof(*p));if(!p)return SLOPH_STATUS_OUT_OF_MEMORY;c->all_binders=p;c->binder_cap=z;}c->all_binders[c->binder_count++]=b->name;return wf(c,b->type,b->span,vars,n);}
static SlophCoreType tint={.kind=SLOPH_TYPE_INT},tbytes={.kind=SLOPH_TYPE_BYTES},tbool={.kind=SLOPH_TYPE_NAMED,.as.name="sloph::Bool"},tunit={.kind=SLOPH_TYPE_NAMED,.as.name="sloph::Unit"};
static bool primitive(const char*n,int v,SlophCoreType***p,size_t*c,SlophCoreType**r){static SlophCoreType*i2[]={&tint,&tint},*i1[]={&tint},*b1[]={&tbytes};if(!strcmp(n,"int.add")||!strcmp(n,"int.sub")||!strcmp(n,"int.mul")){*p=i2;*c=2;*r=&tint;return true;}if(!v)return false;if(!strcmp(n,"int.equal")||!strcmp(n,"int.less")){*p=i2;*c=2;*r=&tbool;return true;}if(!strcmp(n,"int.to_bytes")){*p=i1;*c=1;*r=&tbytes;return true;}if(!strcmp(n,"bytes.length")){*p=b1;*c=1;*r=&tint;return true;}if(!strcmp(n,"runtime.trap")){*p=b1;*c=1;*r=&tunit;return true;}return false;}
static SlophStatus infer(Check*,SlophCoreExpr*,Env,const char**,size_t,SlophCoreType**);
static SlophStatus infer(Check*c,SlophCoreExpr*x,Env e,const char**vars,size_t n,SlophCoreType**out){
    SlophStatus r;SlophCoreType*a,*b;size_t i;
    switch(x->kind){
    case SLOPH_EXPR_INT:*out=&tint;return SLOPH_STATUS_OK;
    case SLOPH_EXPR_BYTES:if(!c->unit->version)return fail(c,"core.validate.expression_form","byte literals require Core version 1 or later",x->span);*out=&tbytes;return SLOPH_STATUS_OK;
    case SLOPH_EXPR_LOCAL:*out=env_get(e,x->as.name);return *out?SLOPH_STATUS_OK:fail(c,"core.validate.unbound_local","unbound local",x->span);
    case SLOPH_EXPR_GLOBAL:{SlophCoreDefinition*d=def_find(c,x->as.name);if(!d)return fail(c,"core.validate.unknown_global","unknown global definition",x->span);*out=d->type;return SLOPH_STATUS_OK;}
    case SLOPH_EXPR_TYPE:return fail(c,"core.validate.type_expression_position","type arguments are only valid as application arguments",x->span);
    case SLOPH_EXPR_LAM:
      if(x->as.lam.binder.is_type){const char**nv;SlophCoreType*t;if(c->unit->version<2)return fail(c,"core.validate.generic_version","type abstractions require Core version 2 or later",x->span);nv=(const char**)malloc((n+1u)*sizeof(*nv));if(!nv)return SLOPH_STATUS_OUT_OF_MEMORY;if(n)memcpy(nv,vars,n*sizeof(*nv));nv[n]=x->as.lam.binder.name;r=infer(c,x->as.lam.body,e,nv,n+1u,&a);free(nv);if(r!=SLOPH_STATUS_OK)return r;t=(SlophCoreType*)calloc(1,sizeof(*t));if(!t)return SLOPH_STATUS_OUT_OF_MEMORY;t->kind=SLOPH_TYPE_FORALL;t->as.forall.parameter=dupstr(x->as.lam.binder.name);t->as.forall.body=clone_sub(a,"",a);if(!t->as.forall.parameter||!t->as.forall.body){sloph_core_type_destroy(t);return SLOPH_STATUS_OUT_OF_MEMORY;}return temp(c,t,out);}
      else {const char**ns;SlophCoreType**ts;Env ne;SlophCoreType*t;r=binder(c,&x->as.lam.binder,vars,n);if(r!=SLOPH_STATUS_OK)return r;ns=(const char**)malloc((e.count+1)*sizeof(*ns));ts=(SlophCoreType**)malloc((e.count+1)*sizeof(*ts));if(!ns||!ts){free(ns);free(ts);return SLOPH_STATUS_OUT_OF_MEMORY;}if(e.count){memcpy(ns,e.names,e.count*sizeof(*ns));memcpy(ts,e.types,e.count*sizeof(*ts));}ns[e.count]=x->as.lam.binder.name;ts[e.count]=x->as.lam.binder.type;ne=(Env){ns,ts,e.count+1};r=infer(c,x->as.lam.body,ne,vars,n,&a);free(ns);free(ts);if(r!=SLOPH_STATUS_OK)return r;t=(SlophCoreType*)calloc(1,sizeof(*t));if(!t)return SLOPH_STATUS_OUT_OF_MEMORY;t->kind=SLOPH_TYPE_FUNCTION;t->as.function.mode=dupstr(x->as.lam.binder.mode);t->as.function.parameter=clone_sub(x->as.lam.binder.type,"",x->as.lam.binder.type);t->as.function.result=clone_sub(a,"",a);if(!t->as.function.mode||!t->as.function.parameter||!t->as.function.result){sloph_core_type_destroy(t);return SLOPH_STATUS_OUT_OF_MEMORY;}return temp(c,t,out);}
    case SLOPH_EXPR_APP:r=infer(c,x->as.app.function,e,vars,n,&a);if(r!=SLOPH_STATUS_OK)return r;if(x->as.app.argument->kind==SLOPH_EXPR_TYPE){if(a->kind!=SLOPH_TYPE_FORALL)return fail(c,"core.validate.not_polymorphic","type application target is not polymorphic",x->as.app.function->span);r=wf(c,x->as.app.argument->as.type,x->as.app.argument->span,vars,n);if(r!=SLOPH_STATUS_OK)return r;return temp(c,clone_sub(a->as.forall.body,a->as.forall.parameter,x->as.app.argument->as.type),out);}r=infer(c,x->as.app.argument,e,vars,n,&b);if(r!=SLOPH_STATUS_OK)return r;if(a->kind!=SLOPH_TYPE_FUNCTION){char message[1200]={0};size_t z=0;text_add(message,sizeof(message),&z,"application target has non-function type ");type_text(a,message,sizeof(message),&z);return fail(c,"core.validate.not_function",message,x->as.app.function->span);}if(!equal(b,a->as.function.parameter))return fail(c,"core.validate.type_mismatch","expected and actual types differ",x->as.app.argument->span);return temp(c,clone_sub(a->as.function.result,"",a->as.function.result),out);
    case SLOPH_EXPR_LET:{const char**ns;SlophCoreType**ts;Env ne;r=infer(c,x->as.let.value,e,vars,n,&a);if(r!=SLOPH_STATUS_OK)return r;r=binder(c,&x->as.let.binder,vars,n);if(r!=SLOPH_STATUS_OK)return r;if(!equal(a,x->as.let.binder.type))return fail(c,"core.validate.type_mismatch","expected and actual types differ",x->as.let.value->span);ns=(const char**)malloc((e.count+1)*sizeof(*ns));ts=(SlophCoreType**)malloc((e.count+1)*sizeof(*ts));if(!ns||!ts){free(ns);free(ts);return SLOPH_STATUS_OUT_OF_MEMORY;}if(e.count){memcpy(ns,e.names,e.count*sizeof(*ns));memcpy(ts,e.types,e.count*sizeof(*ts));}ns[e.count]=x->as.let.binder.name;ts[e.count]=x->as.let.binder.type;ne=(Env){ns,ts,e.count+1};r=infer(c,x->as.let.body,ne,vars,n,out);free(ns);free(ts);return r;}
    case SLOPH_EXPR_PRIM:{SlophCoreType**ps=NULL,*result=NULL;size_t count=0;if(!primitive(x->as.prim.name,c->unit->version,&ps,&count,&result)){size_t j;for(j=0;j<c->unit->foreign_binding_count;++j)if(strcmp(c->unit->foreign_bindings[j].adapter,"unavailable")&& !strcmp(c->unit->foreign_bindings[j].identity,x->as.prim.name)){ps=c->unit->foreign_bindings[j].parameters;count=c->unit->foreign_bindings[j].parameter_count;result=c->unit->foreign_bindings[j].result;break;}}if(!result)return fail(c,"core.validate.unknown_primitive","unknown primitive",x->span);if(count!=x->as.prim.count)return fail(c,"core.validate.primitive_arity","primitive has wrong argument count",x->span);for(i=0;i<count;++i){r=infer(c,x->as.prim.items[i],e,vars,n,&a);if(r!=SLOPH_STATUS_OK)return r;if(!equal(a,ps[i]))return fail(c,"core.validate.type_mismatch","expected and actual types differ",x->as.prim.items[i]->span);}*out=result;return SLOPH_STATUS_OK;}
    case SLOPH_EXPR_CON:{SlophCoreEnum*en;SlophCoreConstructor*co=con_find(c,x->as.con.constructor,&en);SlophCoreType*t;if(!co)return fail(c,"core.validate.unknown_constructor","unknown constructor",x->span);if(x->as.con.type_argument_count!=en->type_parameter_count)return fail(c,"core.validate.constructor_type_arity","constructor has wrong type argument count",x->span);if(x->as.con.field_count!=co->field_count)return fail(c,"core.validate.constructor_arity","constructor has wrong field count",x->span);for(i=0;i<co->field_count;++i){size_t j;SlophCoreType*expected=clone_sub(co->fields[i].type,"",co->fields[i].type);r=infer(c,x->as.con.fields[i],e,vars,n,&a);if(r!=SLOPH_STATUS_OK){sloph_core_type_destroy(expected);return r;}for(j=0;j<en->type_parameter_count;++j){SlophCoreType*next=clone_sub(expected,en->type_parameters[j],x->as.con.type_arguments[j]);sloph_core_type_destroy(expected);expected=next;}if(!equal(a,expected)){sloph_core_type_destroy(expected);return fail(c,"core.validate.type_mismatch","expected and actual types differ",x->as.con.fields[i]->span);}sloph_core_type_destroy(expected);}t=(SlophCoreType*)calloc(1,sizeof(*t));if(!t)return SLOPH_STATUS_OUT_OF_MEMORY;if(!en->type_parameter_count){t->kind=SLOPH_TYPE_NAMED;t->as.name=dupstr(en->name);}else{t->kind=SLOPH_TYPE_APPLIED;t->as.applied.constructor=dupstr(en->name);t->as.applied.count=en->type_parameter_count;t->as.applied.items=(SlophCoreType**)calloc(en->type_parameter_count,sizeof(*t->as.applied.items));for(i=0;i<en->type_parameter_count;++i)t->as.applied.items[i]=clone_sub(x->as.con.type_arguments[i],"",x->as.con.type_arguments[i]);}return temp(c,t,out);}
    case SLOPH_EXPR_CASE:{SlophCoreEnum*en=NULL;r=infer(c,x->as.case_.scrutinee,e,vars,n,&a);if(r!=SLOPH_STATUS_OK)return r;if(a->kind==SLOPH_TYPE_NAMED)en=enum_find(c,a->as.name);else if(a->kind==SLOPH_TYPE_APPLIED)en=enum_find(c,a->as.applied.constructor);if(!en)return fail(c,"core.validate.case_scrutinee","case scrutinee must have a named nominal type",x->as.case_.scrutinee->span);if(x->as.case_.alternative_count!=en->constructor_count)return fail(c,"core.validate.case_exhaustiveness","case must contain every constructor exactly once",x->span);for(i=0;i<x->as.case_.alternative_count;++i){SlophCoreAlternative*al=&x->as.case_.alternatives[i];SlophCoreEnum*ae;SlophCoreConstructor*co=con_find(c,al->constructor,&ae);const char**ns;SlophCoreType**ts;Env ne;size_t j;if(!co||ae!=en)return fail(c,"core.validate.case_exhaustiveness","case contains foreign constructor",al->span);if(al->binder_count!=co->field_count)return fail(c,"core.validate.alternative_arity","alternative has wrong binder count",al->span);ns=(const char**)malloc((e.count+al->binder_count)*sizeof(*ns));ts=(SlophCoreType**)malloc((e.count+al->binder_count)*sizeof(*ts));if((e.count+al->binder_count)&&(!ns||!ts)){free(ns);free(ts);return SLOPH_STATUS_OUT_OF_MEMORY;}if(e.count){memcpy(ns,e.names,e.count*sizeof(*ns));memcpy(ts,e.types,e.count*sizeof(*ts));}for(j=0;j<al->binder_count;++j){r=binder(c,&al->binders[j],vars,n);if(r!=SLOPH_STATUS_OK){free(ns);free(ts);return r;}ns[e.count+j]=al->binders[j].name;ts[e.count+j]=al->binders[j].type;}ne=(Env){ns,ts,e.count+al->binder_count};r=infer(c,al->body,ne,vars,n,&b);free(ns);free(ts);if(r!=SLOPH_STATUS_OK)return r;if(!equal(b,x->as.case_.result_type))return fail(c,"core.validate.type_mismatch","case result type differs",al->body->span);}*out=x->as.case_.result_type;return SLOPH_STATUS_OK;}
    }return fail(c,"core.validate.expression_form","unknown Core expression representation",x->span);
}
static void refs(Check*c,SlophCoreExpr*x,unsigned char*edge){size_t i;if(x->kind==SLOPH_EXPR_GLOBAL){for(i=0;i<c->unit->definition_count;++i)if(!strcmp(x->as.name,c->unit->definitions[i].name))edge[i]=1;return;}switch(x->kind){case SLOPH_EXPR_LAM:refs(c,x->as.lam.body,edge);break;case SLOPH_EXPR_APP:refs(c,x->as.app.function,edge);refs(c,x->as.app.argument,edge);break;case SLOPH_EXPR_LET:refs(c,x->as.let.value,edge);refs(c,x->as.let.body,edge);break;case SLOPH_EXPR_PRIM:for(i=0;i<x->as.prim.count;++i)refs(c,x->as.prim.items[i],edge);break;case SLOPH_EXPR_CON:for(i=0;i<x->as.con.field_count;++i)refs(c,x->as.con.fields[i],edge);break;case SLOPH_EXPR_CASE:refs(c,x->as.case_.scrutinee,edge);for(i=0;i<x->as.case_.alternative_count;++i)refs(c,x->as.case_.alternatives[i].body,edge);break;default:break;}}
static bool fn_type(SlophCoreType*t){while(t->kind==SLOPH_TYPE_FORALL)t=t->as.forall.body;return t->kind==SLOPH_TYPE_FUNCTION;}
static bool visit(size_t i,size_t n,unsigned char*g,unsigned char*s){size_t j;s[i]=1;for(j=0;j<n;++j)if(g[i*n+j]&&(s[j]==1||(!s[j]&&visit(j,n,g,s))))return true;s[i]=2;return false;}
static bool reachable(size_t from,size_t to,size_t n,unsigned char*g,unsigned char*seen){size_t j;if(from==to)return true;seen[from]=1;for(j=0;j<n;++j)if(g[from*n+j]&&!seen[j]&&reachable(j,to,n,g,seen))return true;return false;}
static SlophStatus declarations(Check*c){size_t i,j,k;SlophStatus r;for(i=0;i<c->unit->type_count;++i){SlophCoreEnum*e=&c->unit->types[i];if(!global_id(e->name))return fail(c,"core.validate.global_identity","invalid type identity",e->span);for(j=0;j<i;++j)if(!strcmp(e->name,c->unit->types[j].name))return fail(c,"core.validate.duplicate_type","duplicate type",e->span);if(e->type_parameter_count&&c->unit->version<2)return fail(c,"core.validate.generic_version","generic declarations require Core version 2 or later",e->span);if(e->owned&&c->unit->version!=3)return fail(c,"core.validate.owned_version","owned declarations require Core version 3",e->span);for(j=0;j<e->constructor_count;++j){SlophCoreConstructor*co=&e->constructors[j];size_t p=strlen(e->name);if(strncmp(co->name,e->name,p)||strncmp(co->name+p,"::",2)||!local_id(co->name+p+2))return fail(c,"core.validate.constructor_identity","constructor must be directly qualified by its type",co->span);for(k=0;k<co->field_count;++k){if(!c->unit->version&&co->fields[k].type->kind==SLOPH_TYPE_FUNCTION)return fail(c,"core.validate.function_field","Core v0 nominal fields cannot have function type",co->fields[k].span);r=wf(c,co->fields[k].type,co->fields[k].span,(const char**)e->type_parameters,e->type_parameter_count);if(r!=SLOPH_STATUS_OK)return r;}}}for(i=0;i<c->unit->definition_count;++i){if(!global_id(c->unit->definitions[i].name))return fail(c,"core.validate.global_identity","invalid definition identity",c->unit->definitions[i].span);for(j=0;j<i;++j)if(!strcmp(c->unit->definitions[i].name,c->unit->definitions[j].name))return fail(c,"core.validate.duplicate_definition","duplicate definition",c->unit->definitions[i].span);r=wf(c,c->unit->definitions[i].type,c->unit->definitions[i].span,NULL,0);if(r!=SLOPH_STATUS_OK)return r;}return SLOPH_STATUS_OK;}
static bool owned(Check*c,SlophCoreType*t){SlophCoreEnum*e=NULL;if(t->kind==SLOPH_TYPE_NAMED)e=enum_find(c,t->as.name);else if(t->kind==SLOPH_TYPE_APPLIED)e=enum_find(c,t->as.applied.constructor);return e&&e->owned;}
static size_t uses(SlophCoreExpr*x,const char*n){size_t z=0,i;if(x->kind==SLOPH_EXPR_LOCAL)return !strcmp(x->as.name,n);switch(x->kind){case SLOPH_EXPR_LAM:return uses(x->as.lam.body,n);case SLOPH_EXPR_APP:return uses(x->as.app.function,n)+uses(x->as.app.argument,n);case SLOPH_EXPR_LET:return uses(x->as.let.value,n)+uses(x->as.let.body,n);case SLOPH_EXPR_PRIM:for(i=0;i<x->as.prim.count;++i)z+=uses(x->as.prim.items[i],n);break;case SLOPH_EXPR_CON:for(i=0;i<x->as.con.field_count;++i)z+=uses(x->as.con.fields[i],n);break;case SLOPH_EXPR_CASE:z=uses(x->as.case_.scrutinee,n);for(i=0;i<x->as.case_.alternative_count;++i)z+=uses(x->as.case_.alternatives[i].body,n);break;default:break;}return z;}
static SlophStatus ownership(Check*c,SlophCoreExpr*x){size_t i;SlophStatus r;if(x->kind==SLOPH_EXPR_LAM&&!x->as.lam.binder.is_type&&owned(c,x->as.lam.binder.type)&&!strcmp(x->as.lam.binder.mode,"own")){size_t n=uses(x->as.lam.body,x->as.lam.binder.name);if(!n){char message[256],details[256];(void)snprintf(message,sizeof(message),"owned parameter '%s' is not consumed",x->as.lam.binder.name);(void)snprintf(details,sizeof(details),"{\"local\":\"%s\"}",x->as.lam.binder.name);return fail_details(c,"core.validate.owned_not_consumed",message,details,x->as.lam.binder.span);}if(n>1)return fail(c,"core.validate.use_after_move","owned local is used after it was moved",x->as.lam.binder.span);}switch(x->kind){case SLOPH_EXPR_LAM:return ownership(c,x->as.lam.body);case SLOPH_EXPR_APP:r=ownership(c,x->as.app.function);return r==SLOPH_STATUS_OK?ownership(c,x->as.app.argument):r;case SLOPH_EXPR_LET:r=ownership(c,x->as.let.value);return r==SLOPH_STATUS_OK?ownership(c,x->as.let.body):r;case SLOPH_EXPR_PRIM:for(i=0;i<x->as.prim.count;++i)if((r=ownership(c,x->as.prim.items[i]))!=SLOPH_STATUS_OK)return r;break;case SLOPH_EXPR_CON:for(i=0;i<x->as.con.field_count;++i)if((r=ownership(c,x->as.con.fields[i]))!=SLOPH_STATUS_OK)return r;break;case SLOPH_EXPR_CASE:if((r=ownership(c,x->as.case_.scrutinee))!=SLOPH_STATUS_OK)return r;for(i=0;i<x->as.case_.alternative_count;++i)if((r=ownership(c,x->as.case_.alternatives[i].body))!=SLOPH_STATUS_OK)return r;break;default:break;}return SLOPH_STATUS_OK;}
SlophStatus sloph_core_validate(SlophContext*ctx,SlophCoreUnit*unit){Check c={0};SlophStatus r;size_t i,n;unsigned char*g=NULL,*s=NULL;Env empty={0};if(!ctx||!unit)return SLOPH_STATUS_INVALID_ARGUMENT;c.ctx=ctx;c.unit=unit;if(unit->version<0||unit->version>3){r=fail(&c,"core.validate.unsupported_version","only Core versions 0, 1, 2, and 3 are supported",unit->span);goto done;}if(!unit->version&&unit->foreign_binding_count){r=fail(&c,"core.validate.foreign_version","foreign bindings require Core version 1 or later",unit->span);goto done;}if((r=declarations(&c))!=SLOPH_STATUS_OK)goto done;n=unit->definition_count;g=(unsigned char*)calloc(n?n*n:1,1);s=(unsigned char*)calloc(n?n:1,1);if(!g||!s){r=SLOPH_STATUS_OUT_OF_MEMORY;goto done;}for(i=0;i<n;++i)if(!(unit->version>=1&&fn_type(unit->definitions[i].type)))refs(&c,unit->definitions[i].value,g+i*n);for(i=0;i<n;++i)if(!s[i]&&visit(i,n,g,s)){char details[4096]="{\"definitions\":[";size_t used=strlen(details),j;bool first=true;for(j=0;j<n;++j){unsigned char*seen1=(unsigned char*)calloc(n?n:1,1),*seen2=(unsigned char*)calloc(n?n:1,1);bool member=seen1&&seen2&&reachable(i,j,n,g,seen1)&&reachable(j,i,n,g,seen2);free(seen1);free(seen2);if(member){int z=snprintf(details+used,sizeof(details)-used,"%s\"%s\"",first?"":",",unit->definitions[j].name);if(z>0)used+=(size_t)z;first=false;}}(void)snprintf(details+used,sizeof(details)-used,"]}");r=fail_details(&c,"core.validate.global_cycle",unit->version?"Core value definitions must be acyclic":"Core v0 value definitions must be acyclic",details,unit->definitions[i].span);goto done;}for(i=0;i<n;++i){SlophCoreType*t;c.binder_count=0;if((r=infer(&c,unit->definitions[i].value,empty,NULL,0,&t))!=SLOPH_STATUS_OK)goto done;if(!equal(t,unit->definitions[i].type)){char actual[1024]={0},expected[1024]={0},message[2600],details[2600];size_t al=0,el=0;type_text(t,actual,sizeof(actual),&al);type_text(unit->definitions[i].type,expected,sizeof(expected),&el);(void)snprintf(message,sizeof(message),"definition '%s' has type %s, expected %s",unit->definitions[i].name,actual,expected);(void)snprintf(details,sizeof(details),"{\"actual\":\"%s\",\"definition\":\"%s\",\"expected\":\"%s\"}",actual,unit->definitions[i].name,expected);r=fail_details(&c,"core.validate.definition_type",message,details,unit->definitions[i].value->span);goto done;}}if(unit->version==3)for(i=0;i<n;++i){if(!fn_type(unit->definitions[i].type)&&owned(&c,unit->definitions[i].type)){r=fail(&c,"core.validate.owned_global","owned values cannot be stored in process-lifetime globals",unit->definitions[i].span);goto done;}if((r=ownership(&c,unit->definitions[i].value))!=SLOPH_STATUS_OK)goto done;}r=SLOPH_STATUS_OK;
done:free(g);free(s);free(c.all_binders);for(i=0;i<c.temp_count;++i)sloph_core_type_destroy(c.temps[i]);free(c.temps);return r;}
