#include "syntax_internal.h"

#include <stdio.h>
#include <string.h>

typedef struct Formatter { SlophContext *context; SlophBuffer out; SlophStatus status; } Formatter;
static void putn(Formatter*f,const void*s,size_t n){if(f->status==SLOPH_STATUS_OK)f->status=sloph_buffer_append(&f->out,s,n);}static void puts_(Formatter*f,const char*s){putn(f,s,strlen(s));}static void indent(Formatter*f,size_t n){while(n--)putn(f," ",1u);}

static void target_pattern(Formatter *f, const SlophSyntaxPattern *pattern) {
    size_t i;
    if (pattern->kind == SLOPH_SYNTAX_PATTERN_CONSTANT) {
        puts_(f, pattern->as.constant);
        return;
    }
    puts_(f, "(");
    for (i = 0u; i < pattern->as.tuple.count; ++i) {
        if (i != 0u) puts_(f, ", ");
        target_pattern(f, pattern->as.tuple.items[i]);
    }
    puts_(f, ")");
}
static void direct_import(Formatter *f, const SlophSyntaxDirectImport *import_) {
    size_t i;
    puts_(f, import_->module); puts_(f, "::{");
    for (i = 0u; i < import_->name_count; ++i) {
        if (i != 0u) puts_(f, ", ");
        puts_(f, import_->names[i]);
    }
    puts_(f, "}");
}

static void type_(Formatter*,const SlophSyntaxType*);static void expr(Formatter*,const SlophSyntaxExpr*,size_t);static void block(Formatter*,const SlophSyntaxBlock*,size_t);
static void mode(Formatter*f,const char*m){if(m!=NULL&&strcmp(m,"own")!=0){puts_(f,m);puts_(f," ");}}
static void type_(Formatter*f,const SlophSyntaxType*t){size_t i;switch(t->kind){case SLOPH_SYNTAX_TYPE_INT:puts_(f,"Int");break;case SLOPH_SYNTAX_TYPE_NAMED:puts_(f,t->as.name);break;case SLOPH_SYNTAX_TYPE_INFERRED:puts_(f,"_");break;case SLOPH_SYNTAX_TYPE_APPLIED:puts_(f,t->as.applied.constructor);puts_(f,"[");for(i=0;i<t->as.applied.count;i++){if(i)puts_(f,", ");type_(f,t->as.applied.items[i]);}puts_(f,"]");break;case SLOPH_SYNTAX_TYPE_FUNCTION:puts_(f,"fn(");mode(f,t->as.function.mode);type_(f,t->as.function.parameter);puts_(f,") -> ");type_(f,t->as.function.result);break;}}
static void bytes_(Formatter*f,const unsigned char*d,size_t n){size_t i;char x[5];puts_(f,"\"");for(i=0;i<n;i++){switch(d[i]){case'\n':puts_(f,"\\n");break;case'\r':puts_(f,"\\r");break;case'\t':puts_(f,"\\t");break;case 0:puts_(f,"\\0");break;case'\\':puts_(f,"\\\\");break;case'\"':puts_(f,"\\\"");break;default:if(d[i]>=32u&&d[i]<=126u)putn(f,&d[i],1u);else{(void)snprintf(x,sizeof(x),"\\x%02x",d[i]);puts_(f,x);}}}puts_(f,"\"");}
static void expr(Formatter*f,const SlophSyntaxExpr*e,size_t in){size_t i;switch(e->kind){case SLOPH_SYNTAX_EXPR_INT:puts_(f,e->as.integer);break;case SLOPH_SYNTAX_EXPR_BYTES:bytes_(f,e->as.bytes.data,e->as.bytes.length);break;case SLOPH_SYNTAX_EXPR_LOCAL:case SLOPH_SYNTAX_EXPR_GLOBAL:puts_(f,e->as.name);break;case SLOPH_SYNTAX_EXPR_CALL:expr(f,e->as.call.function,in);if(e->as.call.type_argument_count){puts_(f,"[");for(i=0;i<e->as.call.type_argument_count;i++){if(i)puts_(f,", ");type_(f,e->as.call.type_arguments[i]);}puts_(f,"]");}puts_(f,"(");for(i=0;i<e->as.call.argument_count;i++){if(i)puts_(f,", ");expr(f,e->as.call.arguments[i],in);}puts_(f,")");break;case SLOPH_SYNTAX_EXPR_BINARY:puts_(f,"(");expr(f,e->as.binary.left,in);puts_(f," ");puts_(f,e->as.binary.operator_);puts_(f," ");expr(f,e->as.binary.right,in);puts_(f,")");break;case SLOPH_SYNTAX_EXPR_LAMBDA:puts_(f,"fn(");for(i=0;i<e->as.lambda.parameter_count;i++){if(i)puts_(f,", ");puts_(f,e->as.lambda.parameters[i].name);puts_(f,": ");mode(f,e->as.lambda.parameters[i].mode);type_(f,e->as.lambda.parameters[i].type);}puts_(f,") -> ");type_(f,e->as.lambda.result_type);puts_(f," ");block(f,e->as.lambda.body,in);break;case SLOPH_SYNTAX_EXPR_IF:puts_(f,"if ");expr(f,e->as.if_.condition,in);puts_(f," ");block(f,e->as.if_.then_body,in);puts_(f," else ");block(f,e->as.if_.else_body,in);break;case SLOPH_SYNTAX_EXPR_CONSTRUCTOR:puts_(f,e->as.constructor.constructor);if(e->as.constructor.type_argument_count){puts_(f,"[");for(i=0;i<e->as.constructor.type_argument_count;i++){if(i)puts_(f,", ");type_(f,e->as.constructor.type_arguments[i]);}puts_(f,"]");}puts_(f,"(");for(i=0;i<e->as.constructor.argument_count;i++){if(i)puts_(f,", ");expr(f,e->as.constructor.arguments[i],in);}puts_(f,")");break;case SLOPH_SYNTAX_EXPR_PRIMITIVE:puts_(f,"primitive ");puts_(f,e->as.primitive.name);puts_(f,"(");for(i=0;i<e->as.primitive.argument_count;i++){if(i)puts_(f,", ");expr(f,e->as.primitive.arguments[i],in);}puts_(f,")");break;case SLOPH_SYNTAX_EXPR_CASE:puts_(f,"case ");expr(f,e->as.case_.scrutinee,in);puts_(f," -> ");type_(f,e->as.case_.result_type);puts_(f," {\n");for(i=0;i<e->as.case_.alternative_count;i++){size_t j;SlophSyntaxCaseAlternative*a=&e->as.case_.alternatives[i];indent(f,in+2u);puts_(f,a->constructor);puts_(f,"(");for(j=0;j<a->binder_count;j++){if(j)puts_(f,", ");puts_(f,a->binders[j].name);if(a->binders[j].type->kind!=SLOPH_SYNTAX_TYPE_INFERRED){puts_(f,": ");type_(f,a->binders[j].type);}}puts_(f,") => ");block(f,a->body,in+2u);puts_(f,"\n");}indent(f,in);puts_(f,"}");break;}}
static void block(Formatter*f,const SlophSyntaxBlock*b,size_t in){size_t i;puts_(f,"{\n");for(i=0;i<b->statement_count;i++){const SlophSyntaxStatement*s=&b->statements[i];indent(f,in+2u);if(s->kind==SLOPH_SYNTAX_STMT_DEFER){puts_(f,"defer ");expr(f,s->as.defer_call,in+2u);}else{puts_(f,"let ");puts_(f,s->as.let.binder.name);if(s->as.let.binder.type->kind!=SLOPH_SYNTAX_TYPE_INFERRED){puts_(f,": ");type_(f,s->as.let.binder.type);}puts_(f," = ");expr(f,s->as.let.value,in+2u);}puts_(f,";\n");}indent(f,in+2u);expr(f,b->result,in+2u);puts_(f,"\n");indent(f,in);puts_(f,"}");}
static void type_params(Formatter*f,char**p,size_t n){size_t i;if(!n)return;puts_(f,"[");for(i=0;i<n;i++){if(i)puts_(f,", ");puts_(f,p[i]);}puts_(f,"]");}
SlophStatus sloph_syntax_format(SlophContext*context,const SlophSyntaxModule*m,SlophSyntaxText*out){Formatter f;size_t i,j;char*result;const SlophAllocator*a;if(context==NULL||m==NULL||out==NULL)return SLOPH_STATUS_INVALID_ARGUMENT;out->data=NULL;out->length=0;memset(&f,0,sizeof(f));f.context=context;f.status=SLOPH_STATUS_OK;sloph_buffer_init(&f.out,context,sloph_context_limits(context)->output_bytes);puts_(&f,"module ");puts_(&f,m->name);if(m->availability!=NULL){puts_(&f," when ");puts_(&f,m->availability->selector);puts_(&f," is ");target_pattern(&f,m->availability->pattern);}puts_(&f,";\n");
for(i=0;i<m->import_count;i++){SlophSyntaxImport*x=&m->imports[i];puts_(&f,"\n");if(x->kind==SLOPH_SYNTAX_IMPORT_DIRECT){if(x->as.direct.public_)puts_(&f,"public ");puts_(&f,"import ");direct_import(&f,&x->as.direct);puts_(&f,";\n");}else{puts_(&f,"import case ");puts_(&f,x->as.conditional.selector);puts_(&f," {\n");for(j=0;j<x->as.conditional.alternative_count;j++){SlophSyntaxConditionalAlternative*a=&x->as.conditional.alternatives[j];indent(&f,2u);target_pattern(&f,a->pattern);puts_(&f," => ");direct_import(&f,&a->import_);puts_(&f,";\n");}puts_(&f,"}\n");}}
for(i=0;i<m->type_count;i++){SlophSyntaxTypeDecl*d=&m->types[i];puts_(&f,"\n");if(d->public_)puts_(&f,"public ");if(d->kind==SLOPH_SYNTAX_TYPE_DECL_INTRINSIC){puts_(&f,"intrinsic type ");puts_(&f,d->name);puts_(&f,";\n");continue;}if(d->owned)puts_(&f,"owned ");puts_(&f,"type ");puts_(&f,d->name);type_params(&f,d->type_parameters,d->type_parameter_count);puts_(&f," {\n");for(j=0;j<d->constructor_count;j++){size_t k;indent(&f,2u);puts_(&f,d->constructors[j].name);puts_(&f,"(");for(k=0;k<d->constructors[j].field_count;k++){if(k)puts_(&f,", ");puts_(&f,d->constructors[j].fields[k].name);puts_(&f,": ");type_(&f,d->constructors[j].fields[k].type);}puts_(&f,");\n");}puts_(&f,"}\n");}
for(i=0;i<m->function_count;i++){SlophSyntaxFunction*d=&m->functions[i];puts_(&f,"\n");if(d->public_)puts_(&f,"public ");if(d->kind==SLOPH_SYNTAX_FUNCTION_INTRINSIC)puts_(&f,"intrinsic ");else if(d->kind==SLOPH_SYNTAX_FUNCTION_FOREIGN)puts_(&f,"foreign ");puts_(&f,"fn ");puts_(&f,d->name);type_params(&f,d->type_parameters,d->type_parameter_count);puts_(&f,"(");for(j=0;j<d->parameter_count;j++){if(j)puts_(&f,", ");puts_(&f,d->parameters[j].name);puts_(&f,": ");mode(&f,d->parameters[j].mode);type_(&f,d->parameters[j].type);}puts_(&f,") -> ");type_(&f,d->result_type);if(d->kind==SLOPH_SYNTAX_FUNCTION_DEFINED){puts_(&f," ");block(&f,d->body,0u);puts_(&f,"\n");}else{puts_(&f," = ");puts_(&f,d->binding);puts_(&f,";\n");}}
for(i=0;i<m->value_count;i++){SlophSyntaxValue*d=&m->values[i];puts_(&f,"\n");if(d->public_)puts_(&f,"public ");puts_(&f,m->version==1u?"const ":"value ");puts_(&f,d->name);puts_(&f,": ");type_(&f,d->type);puts_(&f," ");block(&f,d->value,0u);puts_(&f,"\n");}
if(f.status==SLOPH_STATUS_OK)f.status=sloph_buffer_append_byte(&f.out,0u);if(f.status!=SLOPH_STATUS_OK){sloph_buffer_destroy(&f.out);return f.status;}a=sloph_context_allocator(context);result=a->allocate(a->user_data,f.out.length);if(result==NULL){sloph_buffer_destroy(&f.out);return SLOPH_STATUS_OUT_OF_MEMORY;}memcpy(result,f.out.data,f.out.length);out->data=result;out->length=f.out.length-1u;sloph_buffer_destroy(&f.out);return SLOPH_STATUS_OK;}
