#include "syntax_internal.h"

#include <ctype.h>
#include <stdio.h>
#include <string.h>

typedef struct Validator { SlophContext *context; const SlophSyntaxModule *module; size_t nodes, depth; SlophStatus status; } Validator;
static void enter(Validator *, SlophSpan);
static void leave(Validator *);
static void bad(Validator*v,const char*code,const char*message,SlophSpan span){char full[96];if(v->status!=SLOPH_STATUS_OK)return;(void)snprintf(full,sizeof(full),"syntax.validate.%s",code);v->status=sloph_syntax_diagnostic(v->context,full,"validate",message,span,SLOPH_STATUS_INVALID_ARGUMENT);}
static bool lower_name(const char*s){size_t i;if(s==NULL||(!islower((unsigned char)s[0])&&s[0]!='_'))return false;for(i=1u;s[i];i++)if(!isalnum((unsigned char)s[i])&&s[i]!='_')return false;return true;}
static bool upper_name(const char*s){size_t i;if(s==NULL||!isupper((unsigned char)s[0]))return false;for(i=1u;s[i];i++)if(!isalnum((unsigned char)s[i])&&s[i]!='_')return false;return true;}
static int target_pattern(Validator *v, const SlophSyntaxPattern *pattern) {
    size_t i;
    if (pattern == NULL) { bad(v,"invalid_target","invalid compiler-target pattern",SLOPH_UNKNOWN_SPAN); return 0; }
    enter(v, pattern->span);
    if (pattern->kind == SLOPH_SYNTAX_PATTERN_CONSTANT) {
        int result = 0;
        if (strcmp(pattern->as.constant,"os::linux")==0 || strcmp(pattern->as.constant,"os::darwin")==0) result=1;
        else if (strcmp(pattern->as.constant,"arch::amd64")==0 || strcmp(pattern->as.constant,"arch::arm64")==0) result=2;
        else bad(v,"invalid_target","unknown compiler-target constant",pattern->span);
        leave(v); return result;
    }
    if (pattern->kind != SLOPH_SYNTAX_PATTERN_TUPLE || pattern->as.tuple.count != 2u) {
        bad(v,"invalid_target","compiler-target tuple pattern must contain os and arch",pattern->span); leave(v); return 0;
    }
    i=(size_t)target_pattern(v,pattern->as.tuple.items[0]);
    i=i*10u+(size_t)target_pattern(v,pattern->as.tuple.items[1]);
    if(i!=12u)bad(v,"target_type","compiler-target tuple pattern must contain os then arch",pattern->span);
    leave(v); return (int)i;
}
static int selector_kind(const char *selector) {
    if (selector && strcmp(selector,"compiler::target::arch")==0) return 2;
    if (selector && strcmp(selector,"compiler::target::platform")==0) return 12;
    return 0;
}
static void enter(Validator*v,SlophSpan s){const SlophLimits*l=sloph_context_limits(v->context);v->nodes++;v->depth++;if(s.end<s.start)bad(v,"invalid_span","node span must contain ordered non-negative byte offsets",s);else if(s.end>l->input_bytes)bad(v,"limit_exceeded","input_bytes limit exceeded",s);else if(v->nodes>l->ast_nodes)bad(v,"limit_exceeded","ast_nodes limit exceeded",s);else if(v->depth>l->syntax_depth)bad(v,"limit_exceeded","syntax_depth limit exceeded",s);}
static void leave(Validator*v){if(v->depth)v->depth--;}
static void type_(Validator*,const SlophSyntaxType*);static void expr(Validator*,const SlophSyntaxExpr*);static void block(Validator*,const SlophSyntaxBlock*);
static void type_(Validator*v,const SlophSyntaxType*t){size_t i;if(t==NULL){bad(v,"wrong_node","expected source type",SLOPH_UNKNOWN_SPAN);return;}enter(v,t->span);switch(t->kind){case SLOPH_SYNTAX_TYPE_INT:break;case SLOPH_SYNTAX_TYPE_NAMED:if(t->as.name==NULL)bad(v,"invalid_name","named type requires a name",t->span);break;case SLOPH_SYNTAX_TYPE_APPLIED:if(v->module->version==0u||t->as.applied.count==0u)bad(v,"wrong_node","generic types require Source v1",t->span);for(i=0u;i<t->as.applied.count;i++)type_(v,t->as.applied.items[i]);break;case SLOPH_SYNTAX_TYPE_FUNCTION:if(strcmp(t->as.function.mode,"own")&&strcmp(t->as.function.mode,"borrow")&&strcmp(t->as.function.mode,"borrow-mut"))bad(v,"parameter_mode","parameter mode must be own, borrow, or borrow-mut",t->span);type_(v,t->as.function.parameter);type_(v,t->as.function.result);break;case SLOPH_SYNTAX_TYPE_INFERRED:if(v->module->version==0u)bad(v,"wrong_node","inferred types require Source v1",t->span);break;default:bad(v,"unknown_node","unknown syntax type",t->span);}leave(v);}
static void binder(Validator*v,const SlophSyntaxBinder*b){if(!lower_name(b->name))bad(v,"invalid_name","binder must start with lowercase or underscore",b->span);type_(v,b->type);}
static void block(Validator*v,const SlophSyntaxBlock*b){size_t i;if(b==NULL){bad(v,"wrong_node","expected block",SLOPH_UNKNOWN_SPAN);return;}enter(v,b->span);for(i=0u;i<b->statement_count;i++){const SlophSyntaxStatement*s=&b->statements[i];enter(v,s->span);if(s->kind==SLOPH_SYNTAX_STMT_LET){binder(v,&s->as.let.binder);expr(v,s->as.let.value);}else if(s->kind==SLOPH_SYNTAX_STMT_DEFER){if(v->module->version!=1u||s->as.defer_call==NULL||s->as.defer_call->kind!=SLOPH_SYNTAX_EXPR_CALL)bad(v,"defer_call","defer requires a Source v1 function call",s->span);expr(v,s->as.defer_call);}else bad(v,"wrong_node","unknown block statement",s->span);leave(v);}expr(v,b->result);leave(v);}
static void expr(Validator*v,const SlophSyntaxExpr*e){size_t i;if(e==NULL){bad(v,"wrong_node","expected source expression",SLOPH_UNKNOWN_SPAN);return;}enter(v,e->span);switch(e->kind){case SLOPH_SYNTAX_EXPR_INT:if(e->as.integer==NULL)bad(v,"invalid_integer","integer value is missing",e->span);break;case SLOPH_SYNTAX_EXPR_BYTES:break;case SLOPH_SYNTAX_EXPR_LOCAL:if(!lower_name(e->as.name))bad(v,"invalid_name","local name must start with lowercase or underscore",e->span);break;case SLOPH_SYNTAX_EXPR_GLOBAL:if(strstr(e->as.name,"::")==NULL)bad(v,"invalid_name","global name must be qualified",e->span);break;case SLOPH_SYNTAX_EXPR_CALL:if(v->module->version==0u&&(e->as.call.argument_count==0u||(e->as.call.function->kind!=SLOPH_SYNTAX_EXPR_LOCAL&&e->as.call.function->kind!=SLOPH_SYNTAX_EXPR_GLOBAL)))bad(v,e->as.call.argument_count==0u?"call_arity":"dynamic_call",e->as.call.argument_count==0u?"Source v0 calls require at least one argument":"calls must directly name a function",e->span);expr(v,e->as.call.function);for(i=0u;i<e->as.call.argument_count;i++)expr(v,e->as.call.arguments[i]);for(i=0u;i<e->as.call.type_argument_count;i++)type_(v,e->as.call.type_arguments[i]);break;case SLOPH_SYNTAX_EXPR_BINARY:if(v->module->version!=1u)bad(v,"invalid_operator","binary operators require Source v1",e->span);expr(v,e->as.binary.left);expr(v,e->as.binary.right);break;case SLOPH_SYNTAX_EXPR_LAMBDA:if(v->module->version!=1u)bad(v,"wrong_node","lambda expressions require Source v1",e->span);for(i=0u;i<e->as.lambda.parameter_count;i++)binder(v,&e->as.lambda.parameters[i]);type_(v,e->as.lambda.result_type);block(v,e->as.lambda.body);break;case SLOPH_SYNTAX_EXPR_IF:if(v->module->version!=1u)bad(v,"wrong_node","if expressions require Source v1",e->span);expr(v,e->as.if_.condition);block(v,e->as.if_.then_body);block(v,e->as.if_.else_body);break;case SLOPH_SYNTAX_EXPR_CONSTRUCTOR:for(i=0u;i<e->as.constructor.argument_count;i++)expr(v,e->as.constructor.arguments[i]);for(i=0u;i<e->as.constructor.type_argument_count;i++)type_(v,e->as.constructor.type_arguments[i]);break;case SLOPH_SYNTAX_EXPR_PRIMITIVE:if(v->module->version!=0u)bad(v,"wrong_node","primitive expressions are not part of Source v1",e->span);for(i=0u;i<e->as.primitive.argument_count;i++)expr(v,e->as.primitive.arguments[i]);break;case SLOPH_SYNTAX_EXPR_CASE:expr(v,e->as.case_.scrutinee);type_(v,e->as.case_.result_type);for(i=0u;i<e->as.case_.alternative_count;i++){size_t j;SlophSyntaxCaseAlternative*a=&e->as.case_.alternatives[i];enter(v,a->span);for(j=0u;j<a->binder_count;j++)binder(v,&a->binders[j]);block(v,a->body);leave(v);}break;default:bad(v,"unknown_node","unknown syntax expression",e->span);}leave(v);}
SlophStatus sloph_syntax_validate(SlophContext*context,const SlophSyntaxModule*m){Validator v;size_t i,j;if(context==NULL||m==NULL||m->version>1u)return SLOPH_STATUS_INVALID_ARGUMENT;memset(&v,0,sizeof(v));v.context=context;v.module=m;v.status=SLOPH_STATUS_OK;enter(&v,m->span);if(m->name==NULL)bad(&v,"invalid_name","module requires a name",m->span);if(m->availability!=NULL){int expected=selector_kind(m->availability->selector);int actual=target_pattern(&v,m->availability->pattern);if(m->version!=1u||expected==0)bad(&v,"invalid_target","invalid compiler-target availability",m->availability->span);else if(actual!=expected)bad(&v,"target_type","compiler-target pattern does not match selector type",m->availability->span);}for(i=0u;i<m->import_count;i++){SlophSyntaxImport*import_=&m->imports[i];enter(&v,import_->span);if(import_->kind==SLOPH_SYNTAX_IMPORT_CONDITIONAL){int expected=selector_kind(import_->as.conditional.selector);for(j=0u;j<import_->as.conditional.alternative_count;j++){int actual=target_pattern(&v,import_->as.conditional.alternatives[j].pattern);size_t k;if(actual!=expected)bad(&v,"target_type","compiler-target pattern does not match selector type",import_->as.conditional.alternatives[j].span);for(k=0u;k<j;k++){SlophSyntaxPattern*a=import_->as.conditional.alternatives[k].pattern,*b=import_->as.conditional.alternatives[j].pattern;if(a->kind==SLOPH_SYNTAX_PATTERN_CONSTANT&&b->kind==SLOPH_SYNTAX_PATTERN_CONSTANT&&strcmp(a->as.constant,b->as.constant)==0)bad(&v,"invalid_import","invalid or duplicate conditional import alternative",import_->span);}}}leave(&v);}for(i=0u;i<m->type_count;i++){const SlophSyntaxTypeDecl*d=&m->types[i];enter(&v,d->span);if(!upper_name(d->name))bad(&v,"invalid_declaration","type must have an uppercase name",d->span);for(j=0u;j<d->constructor_count;j++){size_t k;for(k=0u;k<d->constructors[j].field_count;k++)type_(&v,d->constructors[j].fields[k].type);}leave(&v);}for(i=0u;i<m->function_count;i++){const SlophSyntaxFunction*f=&m->functions[i];enter(&v,f->span);if(!lower_name(f->name))bad(&v,"invalid_declaration","function must have a lowercase name",f->span);if(m->version==0u&&f->parameter_count==0u)bad(&v,"function_arity","Source v0 functions require at least one parameter",f->span);for(j=0u;j<f->parameter_count;j++)binder(&v,&f->parameters[j]);type_(&v,f->result_type);if(f->kind==SLOPH_SYNTAX_FUNCTION_DEFINED)block(&v,f->body);leave(&v);}for(i=0u;i<m->value_count;i++){enter(&v,m->values[i].span);type_(&v,m->values[i].type);block(&v,m->values[i].value);leave(&v);}leave(&v);return v.status;}
